"""updated job model, remote type now can be nullable

Revision ID: 6930ab1aec27
Revises: 03789dc7529c
Create Date: 2026-04-02 13:19:07.629258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6930ab1aec27'
down_revision: Union[str, Sequence[str], None] = '03789dc7529c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'remote_type',
               existing_type=postgresql.ENUM('full_remote', 'part_time', 'office', name='jobremote'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'remote_type',
               existing_type=postgresql.ENUM('full_remote', 'part_time', 'office', name='jobremote'),
               nullable=False)
    # ### end Alembic commands ###
